project:
  type: website
  preview:
    port: 3000
    browser: false
  render: 
    - "*.ipynb"
    - "*.qmd"
    - "!data-viz-aula-completa/"
    
website:
  title: "WV Code - Educação e Consultoria"
  site-url: https://blog.wvcode.com.br
  navbar:
    logo: library/logos/logo_000_wvcode.png
    right:
      - text: Sobre
        href: about.qmd
      - icon: github
        href: https://github.com/wvcode
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: https://blog.wvcode.com.br/index.xml
format:
  html:
    theme: flatly
    css: styles.css





