---
title: "[VDP] - Introdução"
author: "Walter R. Paixão-Côrtes"
date: "2023-02-02"
categories: [Visualização, Python, Pandas, Seaborn]
description: Iniciando com tudo!
---

Olá Devs!!!

A série de Visualização de Dados com Python tem por objetivo habilita-los a utilizar a linguagem Python para: 

- realizar análises de dados em grandes volumes e nos mais diferentes formatos
- criar gráficos que transmitam a informação de maneira agradável e direta
- aprender sobre tipos de visualização de dados que vão além dos gráficos de barras, linhas e tortas.

Ao longo dos posts você irá aprender a utilizar algumas das bibliotecas Python mais famosas na área de Ciência de Dados: Requests, Pandas, Seaborn, MatplotLib, Plotly e muito mais.

Então, não perca mais tempo e comece a leitura agora mesmo!

### AVISO!!!
Essa série de posts é destinada a um público menos experiente, que ainda está aprendendo a programar em Python, bem como aqueles que estão iniciando seu caminho na área de Ciência de Dados. Se você já domina a linguagem, os artigos fora da série de Visualização de Dados com certeza serão mais interessantes!

Um abraço,
Walter.
