name: Publish Blog to Heroku

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write # needed for Cloudflare
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      
      - name: Copy index.php
        run: |
          cp index.php _site/index.php
          cp composer.json _site/composer.json
        shell: sh

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-directory: '_site'
          destination-github-username: 'WalterPaixaoCortes'
          destination-repository-name: 'wvcode/blog-conteudo'
          user-email: wpcortes@gmail.com
          target-branch: main